# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChatSample
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'ChatSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ChatSample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChatSample-tvOS

  target 'ChatSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
